# Generated by Django 5.1.3 on 2024-11-18 17:48

import uuid

from django.db import migrations, models

import src.report.domain.value_objects


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DATA_LEAK", "DATA LEAK"),
                            ("INAPPROPRIATE_PRACTICES", "INAPPROPRIATE PRACTICES"),
                            ("SUSPICIOUS_ACTIVITIES", "SUSPICIOUS ACTIVITIES"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=50,
                    ),
                ),
                ("complaint", models.TextField()),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default=src.report.domain.value_objects.ReportStatus["PENDING"],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "db_table": "report",
            },
        ),
    ]
